[tool.poetry]
name = "Vhymn"
version = "0.1.0"
description = ""
authors = ["Mateen ahamed"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
spleeter = "^2.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

