services:
  - type: web
    name: vhymn
    env: python
    buildCommand: poetry install
    startCommand: poetry run python app.py
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    pythonVersion: 3.10.13
