services:
  - type: web
    name: vhymn
    env: python
    plan: free
    region: oregon  # or frankfurt, etc.
    branch: main
    autoDeploy: true
    pythonVersion: 3.10.13
    buildCommand: poetry install
    startCommand: poetry run python app.py
    envVars:
      - key: PORT
        value: 10000
